data:
  raw_path: "data/raw/bike_sharing_raw.csv"
  processed_dir: "data/processed"
  test_size: 0.2
model:
  save_path: "models/bike_model.pkl"

aws:
  endpoint_url: "http://localstack:4566"
  bucket_name: "bike-sharing"
  file_name: "raw.csv"
  region_name: "us-east-1"
  raw_file_key: "raw.csv" 