global:
  scrape_interval: 5s 

scrape_configs:
  - job_name: 'prediction_api'
    static_configs:
      # üëà ‡∞®‡±Å‡∞µ‡±ç‡∞µ‡±Å Windows ‡∞≤‡±ã API ‡∞∞‡∞®‡±ç ‡∞ö‡±á‡∞∏‡±ç‡∞§‡±Å‡∞®‡±ç‡∞®‡∞æ‡∞µ‡±Å ‡∞ï‡∞æ‡∞¨‡∞ü‡±ç‡∞ü‡∞ø host.docker.internal ‡∞µ‡∞æ‡∞°‡∞æ‡∞≤‡∞ø
      # ‡∞í‡∞ï‡∞µ‡±á‡∞≥ ‡∞®‡±Ä API 9999 ‡∞™‡±ã‡∞∞‡±ç‡∞ü‡±ç ‡∞Æ‡±Ä‡∞¶ ‡∞∞‡∞®‡±ç ‡∞Ö‡∞µ‡±Å‡∞§‡±Å‡∞Ç‡∞ü‡±á ‡∞Ö‡∞¶‡∞ø ‡∞ï‡±Ç‡∞°‡∞æ ‡∞Æ‡∞æ‡∞∞‡±ç‡∞ö‡∞æ‡∞≤‡∞ø
      - targets: ['host.docker.internal:9999']